### ISSUE TITLE
git-restore-mtime cuts last character from ignored/untracked files

### ISSUE THREAD

**Issue by AndersGoran** [MestreLion/git-tools#10]
In git-restore-mtime, in the code for finding untracked and ignored files, filespec = line[3:-1] cuts off the last character of filenames. This affects repos where there are e.g. editor backup files, such as "file~". In this case, "file" is added to the list of files that are left untouched by the script. The -1 is not necessary together with line.strip().

**Comment by MestreLion** [comment]
Nice catch! You analysis were right on spot: `line.strip()` was indeed a recent change when adding Python 3 support, and I forgot to adjust `filespec` slicing accordingly.

Thanks for the report!
