### ISSUE TITLE
How do I use this on Windows?

### ISSUE THREAD

**Issue by zeluspudding** [MestreLion/git-tools#25]
I have Python and GIT. I really want to restore meta info when I checkout branches. Do I need to register this script as a pre-hook with git? How do I use this thing? I promise to share your the solution on StackOverflow

**Comment by MestreLion** [comment]
Yes, if you want the script to run automatically on every checkout you need to register it as a pre-hook. However, it is not intended and was not tested this way, so I won't be able to give proper support
