### ISSUE TITLE
Won't work inside TravisCI

### ISSUE THREAD

**Issue by mitchellkrogza** [MestreLion/git-tools#29]
First of all thanks for this script, works great in local environments but I simply for the life of me cannot get git-restore-mtime to work inside a TravisCI environment. Has anyone had any success with using this in TravisCI ??

My issue is being able to get the last modified dates and times correct of certain files in the repo so that they can be written into README.md when I build so that users can look through my page of stats and easily when a certain list I create was last updated.

**Comment by wafer-li** [comment]
Hi @mitchellkrogza 

The idea of the `git-restore-mtime` is to recover mtime from git.

Therefore, it needs a full history of the git repo.

But Travis CI clone with `--depth=50` as default, which make it unable to obtain the full history.

To resolve it, you just simply add a config:

```yml
git:
  depth: false
```

to clone with the full history of your repo

**Comment by mitchellkrogza** [comment]
@wafer-lie thank you so much that solves the riddle. I spent hours on this and that actually crossed my mind at one point but then quickly forgot about it too. I will certainly test this again and thanks so much for the heads up.

**Comment by MestreLion** [comment]
Thanks for the solution, @wafer-li !!!
