### ISSUE TITLE
fatal: mmap failed: Cannot allocate memory

### ISSUE THREAD

**Issue by MestreLion** [MestreLion/git-tools#38]
After running on huge repositories (only seen on Linux Kernel), it may output the following error:

    fatal: mmap failed: Cannot allocate memory

It doesn't seem to affect the script, and all processing and file/dir touches seem to be successful. After the first run, git somehow consider the repository "unclean" (and hence the script cannot run again), and any trivial git command takes several seconds to complete and outputs this error again.

Running `git status` seems to fix everything: the repository is considered "clean" again, git operations take their regular time, and the error message is gone.

**Comment by flowerbug** [comment]
these are just some ideas, i have no real capability at the moment of digging into this further.

have you tried this on more recent kernel versions?

does it matter if swap space is bigger or smaller?

**Comment by kilobyte** [comment]
Do you perhaps have "no overcommit" enabled (`/proc/sys/vm/overcommit_memory` = 2)?  This error is unlikely to happen normally (crash would happen at use rather than allocation time).  The man page says:

* *ENOMEM No memory is available.*
* *ENOMEM The process's maximum number of mappings would have been exceeded.  This error can also occur for unmap(), when unmapping a region in the middle of  an  existing  mapping, since this results in two smaller mappings on  either side of the region being unmapped.*
* *ENOMEM (since Linux 4.7) The process's RLIMIT_DATA limit,  described  in  getrlimit(2), would have been exceeded.*

This error comes from git when it has even less virtual memory than it thought (git's handling of low-memory systems is rather weak).

**Comment by MestreLion** [comment]
> Do you perhaps have "no overcommit" enabled (`/proc/sys/vm/overcommit_memory` = 2)?

Nope, currently at 0 (Ubuntu 18.04). But this error happened when using the now ancient Ubuntu 12.04, so either the kernel or git itself might have fixed this in the meantime. I'll leave this bug open until I'm able to test this on a modern git and kernel, or close it in a few months. At least it's recorded for posterity in case anyone else stumbles on this in the future.

**Comment by MestreLion** [comment]
I can verify this still happens, using Ubuntu 18.04, git 2.17.1 and kernel 5.4.0-67. Tested with `git-restore-mtime` from git on repository https://github.com/torvalds/linux . No other repository triggers this.

```
$ git-restore-mtime
71,499 files to be processed in work dir
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 779 and retry the command.
Statistics:
        61.64 seconds
    4,032,484 log lines processed
      923,403 commits evaluated
        3,993 directories updated
       71,499 files updated
fatal: mmap failed: Cannot allocate memory
```

**Comment by MestreLion** [comment]
A quick google search shows this is not exclusive to `restore-mtime` or even `git` itself. A few related reports I've found, some promising ideas (which must be set by the repository owners when _creating_ the repository data) , and none having an actual solution for `restore-mtime`:
- https://stackoverflow.com/questions/6775242
- https://superuser.com/questions/254083
- https://bugs.launchpad.net/ubuntu/+source/git/+bug/1868716
- https://stackoverflow.com/questions/20652850
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841414

That said, I'll close this and reopen when there's any news or solutions we can try on our end

**Comment by MestreLion** [comment]
Very interesting news: `git restore-mtime --test` does **not** trigger the error! So this **not** caused by `git` after all, but by... `os.utime()`! Yes, when Python actually "touch" the files themselves to change the mtime. What a plot twist!

I'll create a test demo that simply "touches" tens of thousand files to see what happens (the linux kernel contains ~73K files)... but in any case this completely changes the investigation focus

**Comment by MestreLion** [comment]
Good news don't last long: the culprit **is** `git`, just not _my_ git.

First I created a `filelist.txt` with all files from kernel repo using `git ls-files` (`find . -type f` also works), then I ran the following script:

```python
#!/usr/bin/env python3

import argparse
import os
import time

parser = argparse.ArgumentParser(description="Touches a bunch of files")
parser.add_argument('path', metavar='PATH', help="Path to the filelist.")
args = parser.parse_args()
now = time.time()
with open(args.path) as f:
    for line in f:
        path = line.strip()
        os.utime(path, (now, now), follow_symlinks=False)
````

And... it triggered the bug! So it has nothing to with `restore_mtime` or its usage of `git`!

But... if `git` has nothing to do with it and merely touching a bunch of files causes this error, why would **any** subsequent command in that directory, even a harmless `echo` or `true`, behave weird, take a long time and emit the error? How can a directory or repository be "tainted" for _any_ command, and fixed by a git command? How can echo or just hitting `ENTER` with no command trigge...

And then it hit me: the **prompt**! My `PS1` set by `bashrc` perform some git operations to show branch, status, etc. And *THAT* is causing the error! Turned on `set -x` and... BINGO!

```
++ git diff --no-ext-diff --quiet
fatal: mmap failed: Cannot allocate memory
```

Some more testing, and `--quiet` is the flag the causes the error. Other combinations, including `git diff` or `git diff --exit-code` not only does not cause but it _fixes_ the error, similar to `git status`. Weird, but not my problem. It's not Python's `os.utime()` fault either, as regular `touch` also triggers it:

```bash
git status  # to make sure it's "clean"
while read -r path; do
    touch "$path"
done < ../filelist.txt
git diff --quiet
fatal: mmap failed: Cannot allocate memory
```

So `restore-mtime` is conclusively and finally off the hook. This is an issue between massive touching and `git diff --quiet`.

**Comment by kilobyte** [comment]
Well, yes — after any mtime modification, git assumes the files have been modified.  Most commands will re-check if that's actually true (which can take a while the first time after a restore-mtime run), some don't (you may get a spurious -dirty suffix).

This can be worked around by running `git status` (or really, whatever plumbing command it relies on) after restore-mtime.

**Comment by MestreLion** [comment]
As `restore-mtime` performs massive touching, what I _could_ do, besides reporting this bug to `git`, is to run `git status` after touching all files, perhaps conditionally (number of files? on what threshold?)

**Comment by MestreLion** [comment]
All my attempts to run `git status` inside `restore-mtime` to silence the error have failed. Maybe this is due to `os.utime()` being run in the background (it's **much** faster than `touch` in bash), so the status is triggered before all touches are flushed and the error is still triggered. I even tried to insert a 3s pause before `git status`, but no success. Weird, because if I run `git-restore-mtime && git status` it _does_ work.

Anyway, I ended up just adding this to a **KNOWN ISSUES** in the manual, and will move on... this case is finally closed
