### ISSUE TITLE
git-find-uncommitted-repos: readlink problem

### ISSUE THREAD

**Issue by PenelopeFudd** [MestreLion/git-tools#39]
Hi; I downloaded git-tools because of git-restore-mtime, and thought I'd try some of the other jewels here (with MacOS Catalina 10.15.4).

Alas, Apple "thinks different", and the 'readlink' command doesn't have the -f option: 
```
$ git find-uncommitted-repos
readlink: illegal option -- f
usage: readlink [-n] [file ...]
^C
```

Initially, I was going to suggest checking for the existence of 'greadlink' (GNU version, as installed by 'brew'), but when I looked at the code, it appears that the output of readlink is no longer used, and that line could be removed completely!
https://github.com/MestreLion/git-tools/blob/master/git-find-uncommitted-repos#L25

Thanks for writing these great tools!

**Comment by PenelopeFudd** [comment]
Also, the '-v' option doesn't do anything.  :-)

**Comment by MestreLion** [comment]
Thanks for reporting this! Both `mydir` and `-v` are common boilerplate code I use in most of my shell scripts, but were unused in `find-uncommited-repos`. Fixed.

Also, thanks for trying out and testing the other tools, and a special thanks for calling them "jewels"! I'm flattered!
