### ISSUE TITLE
doco :  add example of use, e.g. git restore-mtime

### ISSUE THREAD

**Issue by aavmurphy** [MestreLion/git-tools#42]
Documentation

With the ubuntu (and others?) packages, add scripts are (e.g.)  `/usr/lib/git-core/git-restore-mtime`

cd [git repo]
/usr/lib/git-core/git-restore-mtime

Thanks for git-restore-mtime, 1000x faster than a git log script!

**Comment by kilobyte** [comment]
You're not supposed to use the full path.  Just say `git restore-mtime`, like for any other git command.

**Comment by aavmurphy** [comment]
I didn't realise that. Maybe just add `git restore-mtime` as a example,

**Comment by MestreLion** [comment]
> I didn't realise that. Maybe just add `git restore-mtime` as a doco example to show people coming to this for the first time.

Good idea. I've marked this with the (newly-created) `documentation` label, and will leave the issue open until the docs are updated.
 
> Yours is perfect solution. A real shame its not accepted as part of git.

Wow. This is perhaps the best compliment this project can get. Thank you!

... and to think this all started with [this](http://stackoverflow.com/a/13284229/624066) and [this](https://stackoverflow.com/a/13284558/624066) (the bash script is _still_ the most popular solution, heh)
