### ISSUE TITLE
Change the mtime milliseconds/microseconds to the git commit hash

### ISSUE THREAD

**Issue by skorokithakis** [MestreLion/git-tools#43]
We're using git-restore-mtime to let our build system know that a file has changed. Sometimes, two commits might happen at exactly the same time, making the files changed wrongly have the same mtime, and thus the build system doesn't rebuild them, even though they've changed.

I propose that, since git only has second-accuracy, the milliseconds/microseconds field be set to the first bits of the commit hash. That way, files on different commits will never match, even if they were committed on the same second.

**Comment by MestreLion** [comment]
That is a clever idea and a nice feature that I completely agree.

I'm not sure I'll have the time to implement this myself, but any patches/PRs on this are very welcome.

As an implementation suggestion, I believe the most straightforward way to convert the "first bits of the commit hash" from a string hash to a numerical mili/microsecond amount is `int(hash[:x], 16)`, `x` being the hash length that fits the mili/microseconds field (need some research on this on different platforms/filesystems). That is assuming that field is an integer, which is likely a wrong assumption.

**Comment by MestreLion** [comment]
As an implementation suggestion, I believe the most straightforward way to convert the "first bits of the commit hash" from a string hash to a numerical mili/microsecond amount is int(hash[:x], 16), x being the hash length that fits the mili/microseconds field (need some research on this on different platforms/filesystems).

That is assuming that field is an integer, which is likely a wrong assumption. If that field is a float, `struct.unpack('!f', bytes.fromhex(hash[:8]))[0]` would be a suitable candidate.

**Comment by skorokithakis** [comment]
I will see if I can push this along, thanks!

**Comment by MestreLion** [comment]
> That is assuming that field is an integer, which is likely a wrong assumption. If that field is a float, `struct.unpack('!f', bytes.fromhex(hash[:8]))[0]` would be a suitable candidate.

Also some extra handling would possibly be needed if the integer part is greater than 1000, assuming it represents milliseconds while the fractional part is micro/nano/etc up to the filesystem's supported precision.

I have absolutely zero knowledge on how different filesystems stores timestamps, so all my comments on this are merely educated guesses.

I'd be fine with any solution that gets it right for the major filesystems: Ext/4, NTFS, "Whatever-MacOS-uses-as-default", etc. Any other worth supporting? Is FAT worth it? Comments, suggestions?

**Comment by kilobyte** [comment]
sshfs cuts timestamps to full seconds, scp also loses the fractional parts.  Otherwise, any proper Linux filesystems I know about have 1ns resolution.

**Comment by MestreLion** [comment]
I must be blind or dumb to have missed this: Python's `os.utime()` has built-in support for nanoseconds in its API, so it automatically takes care of platform and filesystem support. We can focus on simply calculating the fractional part and let python do the hard work, no research or homework needed. That makes this feature **much** easier to implement, so I might do it myself.

**Comment by MestreLion** [comment]
@skorokithakis , while halfway through implementing this, I realized something: If I simply use the hash as nano/milliseconds, the timestamps might end up in a _different order_  than the commits. Wouldn't that be an issue? Considering a linear A -> B -> C commit tree, if A and B have the same second then their hash-to-nano might make the time order be B -A -C! How to prevent changing the commit  order while still keeping them with unique timestamps?

**Comment by skorokithakis** [comment]
In that case, instead of using the hash, you can simply set the microseconds to the index of the commit. The first commit gets 0 microseconds, the second 1, the third 2, and so on.

**Comment by MestreLion** [comment]
> In that case, instead of using the hash, you can simply set the microseconds to the index of the commit. The first commit gets 0 microseconds, the second 1, the third 2, and so on.

Hum, nice idea. That index would be generated by me during by enumerating the loop, correct? Because git, AFAIK, does not have the concept of a commit index.

In this case, why bother with hashes _at all_? We could simply use that index as the nanosseconds in all cases, no?

**Comment by skorokithakis** [comment]
> That index would be generated by me during by enumerating the loop, correct?

Yes, exactly.

> We could simply use that index as the nanosseconds in all cases, no?

Yes, exactly :P I mentioned hashes because I didn't care about order in my use case, but why not? Also, you should probably use milliseconds instead of microseconds if it's more compatible (I don't know if it is, just guessing) because people probably won't need more than 1000 commits/sec anyway.

**Comment by MestreLion** [comment]
About the CLI: I'm thinking about `--unique-times` with 3 modes: `on`, `off` and `auto` (the default), which uses the nanosseconds only for commits with repeated timestamps.

**Comment by skorokithakis** [comment]
Why not have it on all the time? The first commit is always 0, so it'll behave the same as now, with nanoseconds set to 0, and subsequent commits will have different ns. There's no need to have an option, in my opinion.

**Comment by kilobyte** [comment]
Remember that git is not restricted to linear history, and different branches will have commits with the same index but different contents.

**Comment by skorokithakis** [comment]
Sure, but ordering there only needs to be consistent, since there's no other way to order those anyway. For those, you could use hashes to produce the indexes, I guess.

**Comment by MestreLion** [comment]
> Why not have it on all the time? The first commit is always 0, so it'll behave the same as now, with nanoseconds set to 0, and subsequent commits will have different ns. There's no need to have an option, in my opinion.

It could be that, too. I'm just afraid to introduce backwards-incompatible features in a non-optional way. Maybe there are use cases where people need/want identical timestamps, or rely on second-resolution. I dunno, I havent settled on that, so suggestions are welcome

**Comment by skorokithakis** [comment]
Oh hmm, you mean for existing commits. Right, that might be an issue. I don't think many people will want that, but you know what they say, with enough users, there will always be someone to rely on each of your bugs.

**Comment by MestreLion** [comment]
> Also, you should probably use milliseconds instead of microseconds if it's more compatible (I don't know if it is, just guessing) because people probably won't need more than 1000 commits/sec anyway.

Good idea. Python's `os.utime()` API is in nanosseconds, but I could multiply by 1000 to theoretically be effective on more filesystems. Possibly unnecessary, but no harm anyway

**Comment by MestreLion** [comment]
> Remember that git is not restricted to linear history, and different branches will have commits with the same index but different contents.

Git is not linear, but `whatchanged` is. If I enumerate the loop the indexes will be unique. The collision chance would be the 2nd pass, where it tries merge commits to find missing files, so I guess I'll use the hashes along with indexes to guaranteee uniqueness.

**Comment by MestreLion** [comment]
About git's non-linearity... I truly hope `whatchanged` keeps commit order using the parent/child relationship between commits even for duplicated timestamps, otherwise our whole talk about using indexes to preserve order will be moot.  And I think it's not worth ensuring proper ordering if git doesn't provide it automatically.

**Comment by MestreLion** [comment]
A million nanosseconds = ~20 bits to play with, so I'd say 8 bits for ordering (from index)  and 12 for uniqueness (from hash, 3 first characters), which leads to...

`ns =(index << 8 + int(hash[:3], 16) % 10**6`

And I hope I'm not over-engineering that! lol

As for CLI, `--unique-times` to enable, and disabled by default. No auto, let's KISS this one.

Comments, suggestions? If everyone if fine with this, it will be part of my next 2021.08 this month

Cheers!

**Comment by kilobyte** [comment]
Is there a reason you'd use only the first millisecond?

**Comment by MestreLion** [comment]
> Is there a reason you'd use only the first millisecond?

Because I'm bad at math and SI units and totally forgot about microseconds, lol. Besides, I should've shifted the index 12 bits, not 8.

Anyway, I just realize I don't need to use the hash _at all_, as I already have a global counter that ensures uniqueness across multiple commits, including the 2nd pass merge commits: `stats['loglines']`. And this makes the formula really trivial:

`ns = idx % 10**9`, or `ns = (idx * 10**6) % 10**9` to use @skorokithakis 's idea on milliseconds .

**Comment by MestreLion** [comment]
Actually, considering NTFS has a [100ns resolution](https://en.wikipedia.org/wiki/NTFS), I guess I'll settle with a simple `ns = idx * 100` (sorry exFAT), and drop the mod because... come on!

**Comment by MestreLion** [comment]
I ended up using microseconds instead of nanoseconds, to be compatible with python's `datetime.datetime()`, which is also the resolution of a 64-bit float timestamp when expressing seconds since the UNIX Epoch, as `git` does.

If all goes well, this will be a part of my new release this month, so care to take current `main` branch for a spin?

**Comment by skorokithakis** [comment]
Thank you! I will try to give it a shot soon, but I just left the company we were using it in, so I don't have access to that code any more.
