### ISSUE TITLE
git-restore-mtime ignore modified files in working directory

### ISSUE THREAD

**Issue by wpwoodjr** [MestreLion/git-tools#51]
`git-utimes` ignores files that are modified in the working directory.  I think this is good default behavior.  With `git-restore-mtime`, your only options are to abort (do nothing) or `--force` and then your modified working directory files have their times set to the commit date, which seems like a bad outcome to me.  I'd prefer if `git-restore-mtime` just didn't touch modified files in the working directory, while perhaps letting the user know that the `--force` option is available if required.

**Comment by MestreLion** [comment]
While implementing this, I remembered why I aborted on dirty repos by default in the first place: processing them opens a real can of worms. For example, these uncommitted changes will make `git-restore-mtime` behave in a weird way:
- Renamed and newly-added files will never be found in log (and force a full search while trying)
- Deleted files will be listed by `git ls-files` but won't be found in filesystem (and thus emit error on `touch()`)
- Who knows what will happen on partial/ongoing `rebase`, `stash pop`, `merge`, etc.
Anyway, just wanted to document some of the corner cases before doing so

**Comment by MestreLion** [comment]
@wpwoodjr and @gebailey , care to try RC2 before I publish the new release?

**Comment by gebailey** [comment]
> @wpwoodjr and @gebailey , care to try RC2 before I publish the new release?

I did some quick tests with RC2 and it seems to behave properly.
