### ISSUE TITLE
A --skip option for restore-mtime?

### ISSUE THREAD

**Issue by t0mm1e** [MestreLion/git-tools#52]
Would a `--skip` option to restore-time be useful?
So not forcing the author/commit time on the uncommited files, but just letting them keep the more recent mtime.
That would seem a more logical approach.

**Comment by MestreLion** [comment]
Since #51 this is already the default, if I understood your request correctly:
- Without `--force`, "dirty" files (anything that shows up on `git status`) are ignored, and not even added to the "total files to be processed"
- With `--force`, files with uncommitted _modifications_ are updated. Uncommitted renames, additions and deletions are still ignored.

Is this what you were asking for?

**Comment by t0mm1e** [comment]
Yes, it seems `--force` does what I would have expected of `--skip`.
Wasn't completely clear in the man.
Thanks!

**Comment by MestreLion** [comment]
> Yes, it seems `--force` does what I would have expected of `--skip`.

Actually, `--force` **will** update dirty files. Ignoring them, as would your suggested `--skip`, is now the default behavior.

>  Wasn't completely clear in the man. Thanks!

Manual was updated recently. Got any suggestions on how to improve it to clarify the new `--force` and default behavior?

**Comment by t0mm1e** [comment]
Hmm,

My --skip option would not update dirty files, it wil skip them, hence the
name, skip.
--force sounds like it force updating of dirty files.
But currently, leaving out the --force parameter does not update any file:

superstore: ERROR: There are local changes in the working directory.
superstore: This could lead to undesirable results for modified files.
superstore: Please, commit your changes (or use --force) and try again.
superstore: Aborting

So I either update all files, even dirty files, or none at all.
I'd like to update the non-dirty files en keep the files dirty 😉


*Thomas van Gulick*
***@***.***
+31651202680 (Telegram, Messenger, WhatsApp)

**Comment by MestreLion** [comment]
It seems you're not running the latest version, 2022.07, released last month, which changed how dirty files are handled by default.

> Hmm, My --skip option would not update dirty files, it wil skip them [...] I'd like to update the non-dirty files en keep the files dirty 

Since v2022.07 that's the default behavior, so it works like your suggested `--skip`

> superstore: ERROR: There are local changes in the working directory.
> superstore: This could lead to undesirable results for modified files.
> superstore: Please, commit your changes (or use --force) and try again.
> superstore: Aborting
> So I either update all files, even dirty files, or none at all

That was the previous behavior.

**Comment by t0mm1e** [comment]
I now have the latest version.
Docs seem on point now.
Default behaviour is now as expected.
Though it is not possible to make `--quiet` also quieten warnings.
