### ISSUE TITLE
SyntaxError: invalid syntax on Python 3.4.3

### ISSUE THREAD

**Issue by ylluminate** [MestreLion/git-tools#56]
When executing the test on an older system (Ubuntu 14.04) with Python 3.4.3, the following occurs:
```
$ git restore-mtime --test
  File "/home/username/bin/git-tools/git-restore-mtime", line 356
    stdout: str = subprocess.check_output(cmdlist, **popen_args)
          ^
SyntaxError: invalid syntax
```

**Comment by MestreLion** [comment]
Thanks for the report!

This is expected, as Python 3.4 has reached its end of life in 2019 and is no longer supported. Currently the minimum supported Python version is 3.6. Which I guess is available for the (also obsolete) Ubuntu 14.04.

Any particular reason to use or require such an ancient Python and OS?
