### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by vraravam** [MestreLion/git-tools#60]
Can you please support installation via homebrew for macos? The restore mtime script is super awesome, but I prefer to install all applications/libraries/tools via homebrew, and so would prefer this.

**Comment by MestreLion** [comment]
Thanks for the compliments!

What does `restore-mtime` need to support homebrew? I don't have macOS, so I have no idea how it works or what kind of support it needs

**Comment by vraravam** [comment]
I have created this repo as something that can be used with homebrew: https://github.com/ferdium/homebrew-ferdium 
in the case of your scripts, they will be considered formulae and not casks - but other than that, everything is similar.

**Comment by MestreLion** [comment]
Formulae, Casks, Tap... this is a whole new area I'm unable to explore right now.

But, as far as I understand, Homebrew a platform/format to package, publish and install software for macOS, similar to what PyPi is for Python and Apt repositories are for Debian/Ubuntu correct?

If so, creating (and maintaining) such a package is a great effort, one I have no time or knowledge to do. And I don't even own a macOS to test it. Usually such packaging is performed downstream and not by the upstream authors. If you have the skills to create and maintain a `restore-mtime` homebrew repository I'll gladly make any adjustments needed to make the source code compatible with it, and accept any PRs that implement it, just tell me what you need!

**Comment by vraravam** [comment]
Yes, let me create a repo that can support a tap for git-tools, and once I can prove that its working, maybe we can transfer ownership. Will ping you in a few days.

**Comment by vraravam** [comment]
I was able to create a tap for this today itself: https://github.com/vraravam/homebrew-git-tools
we can close this issue if you want, and then include this new repo as yet another installation method in your README in the appropriate place.

**Comment by aphedges** [comment]
Homebrew now has an official [`git-tools`](https://formulae.brew.sh/formula/git-tools) formula. Someone added it a month ago (<https://github.com/Homebrew/homebrew-core/commit/9f998617da8eddfc3038e7486381498906025ed2>).

**Comment by vraravam** [comment]
Thanks - closing this ticket based on previous comment.
