### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Daviid-P** [MestreLion/git-tools#68]
![image](https://github.com/MestreLion/git-tools/assets/7734808/d2931c4b-7ca9-41b5-bc27-db040f90f0ee)

I want to think it's a false positive, can you confirm.

**Comment by Daviid-P** [comment]
https://www.virustotal.com/gui/file/aa4003baa4214c0d54a72db3193554a49dec4af4f60bb8d77aca2ce89b386ea2/detection

**Comment by MestreLion** [comment]
I don't know... `git-tools` by itself does not provide any executables. The instructions to build one suggest using `pyinstaller.exe`, where did you get it from? The `build_executable.bat` script downloads it from the [pyinstaller repository](https://github.com/pyinstaller/pyinstaller), so maybe they have more information about it? Can you check for open and known issues there?

If this is a known issue with pyinstaller, I could add the necessary notes and warnings here

**Comment by MestreLion** [comment]
Since this is a clarification issue only, I believe this is fixed by faba1cd
