### ISSUE TITLE
git-restore-mtime fails on Python 3 with non-ASCII filenames

### ISSUE THREAD

**Issue by mkvonarx** [MestreLion/git-tools#9]
The git-restore-mtime script fails when used in the following scenario:
1) Windows with NTFS file system.
2) Filename with UTF-8 characters. My concrete example: "Häuser.txt" with the German umlaut ä fails with the error message "WARNING: not found in log: Hõuser.txt" (you see how the error log message uses a different UTF-8 character, namely õ). Not sure if this happens for all UTF-8 characters, or just the ones that are available in the local 8bit codepage like äöü in Switzerland.

As I have no Python know how, I don't know how to debug/analyze the issue myself. Hope you can help.

btw: thanks for the script! I really like it.

Markus

**Comment by dwfreed** [comment]
So I've been digging into this, and found a bunch of things that will make life much easier for fixing this in the normal case.  But I need to make sure the normal case actually applies here.  @mkvonarx, could you paste the output of `git ls-files -z | xxd` from within git bash in your test repo?

**Comment by wafer-li** [comment]
Hi @MestreLion  @dwfreed 

I wrote a python3 script, which tests successfully with my blog which contains lots of non-ASCII filenames.

https://gist.github.com/wafer-li/a7a62a4423cf39c43dc56d628ff4c365

I think you could take this as an example and let it work with python 2.7 and below.

**Comment by MestreLion** [comment]
> Hi @MestreLion @dwfreed
> 
> I wrote a python3 script, which tests successfully with my blog source which contains lots of non-ASCII filenames.
> 
> https://gist.github.com/wafer-li/a7a62a4423cf39c43dc56d628ff4c365
> 
> I think you could take this as an example and let it work with python 2.7 and below.

Your `-z / -0` usage is a very very neat idea, and I've added a note about it in the source code. I'm also pasting your code here in case your gist ever gets deleted, hope you don't mind it

```python
# -*- coding: utf-8 -*-

import subprocess
import os
import shlex

if __name__ != '__main__':
    raise ImportError("%s should not be used as a module." % __name__)

# 'git ls-files -z | xargs -0 -n1 -I{} -- git log -1 --format="%ct {}" {} | sort'
git_ls_cmd = 'git ls-files -z'
xargs_cmd = 'xargs -0 -n1 -I{} -- git log -1 --format="%ct {}" {}'
sort_cmd = 'sort'

work_dir = os.getcwd()

git_ls_result = subprocess.Popen(shlex.split(git_ls_cmd), stdout=subprocess.PIPE)
xargs_result = subprocess.Popen(shlex.split(xargs_cmd), stdin=git_ls_result.stdout, stdout=subprocess.PIPE)
result = subprocess.check_output('sort', stdin=xargs_result.stdout)

timestamp_file_list = [tuple(it.split(' ', 1)) for it in result.decode('utf-8').split('\n')][:-1]

for timestamp, file_path in timestamp_file_list:
    os.utime(os.path.join(work_dir, file_path), (int(timestamp), int(timestamp)))
```
